# S5PC1XX Platform Support
snd-soc-s5pc1xx-objs := s5pc1xx-pcm.o
snd-soc-s5pc1xx-i2s-v50-objs := s5pc100-i2s-v50.o

obj-$(CONFIG_SND_S5PC1XX_SOC) += snd-soc-s5pc1xx.o
obj-$(CONFIG_SND_SOC_I2S_V50) += snd-soc-s5pc1xx-i2s-v50.o

# S5PC1XX Machine Support
snd-soc-smdkc1xx-wm8580-objs := smdkc100_wm8580.o

obj-$(CONFIG_SND_SMDKC100_WM8580) += snd-soc-smdkc1xx-wm8580.o
