#################################################
# Makefile for FIMG-3D 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_CMM)	+= LogMsg.o CMMMisc.o s3c-cmm.o

EXTRA_CFLAGS += -Idrivers/media/video

