obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_FIMV10)	+= fimv10/
obj-$(CONFIG_VIDEO_FIMV40)	+= fimv40/
obj-$(CONFIG_VIDEO_POST)	+= post/
obj-$(CONFIG_VIDEO_POST)	+= tv/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_JPEG)	+= jpeg/
 
EXTRA_CFLAGS += -Idrivers/media/video

